print("   __       __")
print("   \ '\   /' /")
print("    \   V   /")
print("    /  . .  \ ")
print("   =\   *   /=")
print("    /   ^   \ ")
print("   /\\\     //\ ")
print(' __\  "   "  /__')
print("(______/^\______)")

